apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: logging-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000
  type: NodePort 