apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-servicemonitor
  labels:
    release: prometheus
    app: logging-app
spec:
  selector:
    matchLabels:
      app: logging-app
  endpoints:
  - port: metrics
    path: /metrics
    interval: 15s
    scrapeTimeout: 10s
    scheme: http
    honorLabels: true 